repositories:
  - name: "faas-netes"
    url: "https://openfaas.github.io/faas-netes"
  - name: "minio"
    url: "https://operator.min.io"
  - name: "rancher"
    url: "https://charts.rancher.io"

environments:
  default:
    values:
      - k3s:
          enabled: false
  k3s:
    values:
      - k3s:
          enabled: true




releases:
  - name: "openfaas"
    chart: "faas-netes/openfaas"
    namespace: "openfaas"
    createNamespace: true
    version: 9.0.2
    values:
      - "./values/openfaas.yaml"
    hooks:
      - events: ["prepare"]
        showlogs: true
        command: "kubectl"
        args:
          - "apply"
          - "-k"
          - "kustomize/openfaas/base"

  - name: "minio-operator"
    chart: "minio/operator"
    namespace: "minio-operator"
    version: "4.4.3"

  - name: "k3s-upgrader"
    chart: "rancher/system-upgrade-controller"
    condition: k3s.enabled
    namespace: "cattle-system"
    hooks:
      - events:
          - postsync
        showlogs: false
        command: "kubectl"
        args:
          - apply
          - -k
          - kustomize/k3s/postsync/overlays/{{ env "K3S_CHANNEL" | default "stable" }}
