---
apiVersion: v1
data:
  accesskey: NDkzNDc4MzgtOTQ3OS00ODVhLTgwNmMtYTIxZWUyYzMxYTNk
  secretkey: YjI0YzRkNDYtZmU0OC00ZjU5LWFiMWQtOGFjN2ZiNTlmMGQy
kind: Secret
metadata:
  creationTimestamp: null
  name: minio-creds-secret
  namespace: minio


