---
apiVersion: v1
data:
  CONSOLE_ACCESS_KEY: YWRtaW4=
  CONSOLE_SECRET_KEY: ZDNkZDBhZWEtMjIwMi00ZGU5LTg1MTItYTE4ODJkNjBkYTE0
kind: Secret
metadata:
  creationTimestamp: null
  name: minio-user-1
  namespace: minio

