apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  creationTimestamp: null
  name: minio
  namespace: minio
scheduler:
  name: ""
spec:
  certConfig: {}
  credsSecret:
    name: minio-creds-secret
  image: minio/minio:RELEASE.2022-01-08T03-11-54Z
  imagePullSecret: {}
  mountPath: /export
  pools:
  - affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: v1.min.io/tenant
              operator: In
              values:
              - minio
          topologyKey: kubernetes.io/hostname
    resources: {}
    servers: 1
    volumeClaimTemplate:
      apiVersion: v1
      kind: persistentvolumeclaims
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 2560Mi
        storageClassName: local-path
      status: {}
    volumesPerServer: 4
  requestAutoCert: true
  users:
  - name: minio-user-1
status:
  availableReplicas: 0
  certificates: {}
  currentState: ""
  pools: null
  revision: 0
  syncVersion: ""
  usage: {}

